### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by jeronimoirazabal** [redefiance/atom-go-find-references#11]
[Enter steps to reproduce below:]

1. Just searched for references (keyboard shortcut) on an empty file

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.5
**Thrown From**: [go-find-references](https://github.com/redefiance/atom-go-find-references) package, v1.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'substring' of undefined

```
At /Users/jeronimo/.atom/packages/go-find-references/lib/go-find-references-view.coffee:65

TypeError: Cannot read property 'substring' of undefined
    at GoFindReferencesView.module.exports.GoFindReferencesView.trigger (/Users/jeronimo/.atom/packages/go-find-references/lib/go-find-references-view.coffee:65:25)
    at atom-text-editor.<anonymous> (/Users/jeronimo/.atom/packages/go-find-references/lib/go-find-references-view.coffee:43:8)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/jeronimo/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/jeronimo/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/jeronimo/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/jeronimo/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/jeronimo/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Users/jeronimo/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:08.3.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -0:00.7.0 go-find-references:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "go-debug"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.3.0
autocomplete-go, v1.1.0
builder-go, v1.0.0
go-config, v1.1.4
go-find-references, v1.2.3
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
linter, v1.11.3
linter-golint, v0.3.0
navigator-godef, v1.0.3
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by jeronimoirazabal** [comment]
The error take places just on an unsaved new file, because filepath = buffer.getPath() is undef.
